[package]
name = "simple_scene"
version = "0.1.0"
authors = ["Siebencorgie <siebencorgie@googlemail.com>"]

[dependencies]
ori-engine = { path = "../../" }

vulkano = "0.5.6"
vulkano-shader-derive = "0.5.6"
vulkano-win = "0.5.6"
